app:
  name: restful-example
  version: 1.1.0
server:
  port: 9000
  address: 0.0.0.0
logging:
  level: 5  #0 panic 0 fatal 1 error 2 warn 3 info 4 debug 5 trace 6
  report-caller: true
  no-colors: true
  caller-first: true